# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
