# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_registercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMatterExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('profile', models.TextField()),
                ('subjects', models.TextField()),
            ],
        ),
    ]
