# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_auto_20161003_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.TextField(default='overview'),
            preserve_default=False,
        ),
    ]
