# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_courses_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.CharField(default='try', max_length=20),
            preserve_default=False,
        ),
    ]
